// @ts-check
'use client';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "../tooltip";

/**
 * Simplified date header with tooltip for data tables.
 * Expects date strings in the format generated by generateDates() utility:
 * - Day: "2025-12-24" (YYYY-MM-DD)
 * - Week: "2025-W46" (YYYY-W##)
 * - Month: "2025-11" (YYYY-MM)
 * - Year: "2025" (YYYY)
 *
 * @param {Object} props
 * @param {import('@/types/general/DateString.types').DateString} props.date - Date string from generateDates() output
 * @returns {React.JSX.Element}
 */
export default function DateHeader({ date }) {
  /** @type {string} */
  let displayHeader = date;
  /** @type {string} */
  let fullHeader = date;

  // Infer format from the date string pattern
  if (/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    // Day format: "2025-12-24" → display "12-24"
    displayHeader = date.substring(5);
    fullHeader = date;
  } else if (/^\d{4}-W\d+$/.test(date)) {
    // Week format: "2025-W46" → display "W46"
    const weekMatch = date.match(/\d{4}-(W\d+)/);
    if (weekMatch) {
      displayHeader = weekMatch[1];
      fullHeader = date;
    }
  } else if (/^\d{4}-\d{2}$/.test(date)) {
    // Month format: "2025-12" → display "Dec"
    const monthMatch = date.match(/\d{4}-(\d{2})/);
    if (monthMatch) {
      const month_index = parseInt(monthMatch[1], 10) - 1;
      const month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      displayHeader = month_names[month_index];
      fullHeader = date;
    }
  }
  // Year ("2025") format remains as-is

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className="cursor-help">{displayHeader}</span>
        </TooltipTrigger>
        <TooltipContent>
          <p className="text-sm">{fullHeader}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
